# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant::Config.run do |config|

  # Every Vagrant virtual environment requires a box to build off of.
  config.vm.box = "work_squeeze"
  config.vm.box_url = "http://dl.dropbox.com/u/937870/VMs/squeeze64.box"

  # Boot with a GUI so you can see the screen. (Default is headless)
  # config.vm.boot_mode = :gui

  # Changes the memory allocation, now its 512Mb for VM
  config.vm.customize ["modifyvm", :id, "--memory", 512]

  # Network setting, which i don't currently understand
  # config.vm.network :bridged
  # ------------------------

  # port forwarding, 80 on my machine to 8080 on VM
  config.vm.forward_port 80, 8080

  # Расшариваем на VM папку с проектами, "ярлык" - "путь на VM" - "путь локально"
  config.vm.share_folder "apps", "/apps", "/apps"

  # Включаем chef_solo и конфигурируем его

   config.vm.provision :chef_solo do |chef|
     chef.cookbooks_path = ["../my-recipes/cookbooks", "../my-recipes/kaize-cookbooks"]
     chef.roles_path = "../my-recipes/roles"
    # chef.data_bags_path = "../my-recipes/data_bags"
     chef.add_recipe "workvm"
    # chef.add_recipe "postgresql"
      chef.add_role "base"

     # You may also specify custom JSON attributes:
     # chef.json = { :mysql_password => "foo" }
   end

  # Enable provisioning with chef server, specifying the chef server URL,
  # and the path to the validation key (relative to this Vagrantfile).
  #
  # The Opscode Platform uses HTTPS. Substitute your organization for
  # ORGNAME in the URL and validation key.
  #
  # If you have your own Chef Server, use the appropriate URL, which may be
  # HTTP instead of HTTPS depending on your configuration. Also change the
  # validation key to validation.pem.
  #
  # config.vm.provision :chef_client do |chef|
  #   chef.chef_server_url = "https://api.opscode.com/organizations/ORGNAME"
  #   chef.validation_key_path = "ORGNAME-validator.pem"
  # end
  #
  # If you're using the Opscode platform, your validator client is
  # ORGNAME-validator, replacing ORGNAME with your organization name.
  #
  # IF you have your own Chef Server, the default validation client name is
  # chef-validator, unless you changed the configuration.
  #
  #   chef.validation_client_name = "ORGNAME-validator"
end
